version: "3.7"
services: 
    elastic:
        image: "elasticsearch:7.6.1"
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: "single-node"
